### ISSUE TITLE
Bug Report | Feature Idea: Raising AssertionError when running the test

### ISSUE THREAD

**Issue by littlewhitecloud** [Moosems/salve#6]
**Bug Report:**

How to reproduce: run the test_ipc.py
What should happen instead: raise `AssertionError`
Minimum reproducible example:
the test

Traceback:
```console
Traceback (most recent call last):
  File "c:\...\salve-master\tests\test_ipc.py", line 64, in <module>
    test_IPC()
  File "c:\...\salve-master\tests\test_ipc.py", line 32, in test_IPC
    assert autocomplete_output == {
AssertionError
```

<details>

OS: Windows
Git branch: main
Commit that bug started: latest commit

</details>

---

Feature report:

Explain your idea, how it could be implemented, and why it should be added. The more detail you give, the more likely it is to be added. Code snippets that could help add it are _highly recommend_.

**Comment by Moosems** [comment]
@littlewhitecloud When you print out the output, what does it give? Are you running locally installed or from pip?

**Comment by Moosems** [comment]
It doesn't fail in the automatic check (see the pytest workflow). The library is not developed with Windows in mind so it's great to see it works in any capacity without any focus on it :D.

**Comment by Moosems** [comment]
Closing due to no response

**Comment by littlewhitecloud** [comment]
Hmm, I'm sorry that I forgot this issue, I just got it from github directly and ran it without any change.

**Comment by Moosems** [comment]
Can you try updating and running the tests again?
